#! /bin/bash

echo ' '
read -p 'Would you like to clear the previous map database? (y/n): ' ansinput

if [ “$ansinput” = “y” ]
then
 printf '\n Map deleted \n'
 rm -f ~/.ros/rtabmap.db

elif [ “$ansinput” = “n” ]
then
 printf '\n Map kept \n'

else
 echo 'Warning: Not an acceptable option. Choose (y/n).
         '
fi

echo ' '

read -p 'Enter target world destination or d for default: ' input_choice

if [ “$input_choice” = “d” ]
then
 x-terminal-emulator -x roslaunch my_droid my_droid_world.launch world_file:=/home/nvidia/catkin_ws/src/slam_project/worlds/kitchen_dining.world 

else
 x-terminal-emulator -x roslaunch my_droid my_droid_world.launch world_file:=$input_choice 
fi

sleep 3 &&

x-terminal-emulator -x roslaunch my_droid teleop.launch  

sleep 3 &&

echo ' '
read -p 'Press any key to continue to mapping... ' -n1 -s

x-terminal-emulator -x roslaunch my_droid mapping.launch simulation:=true 
sleep 3 &&
x-terminal-emulator -e roslaunch my_droid rviz.launch 

echo ' '
echo 'Script Completed'
echo ' '
